#!/usr/bin/env bash
# Install nginx on your web-01 server
sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R ubuntu /var/www/
echo "Holberton School for the win!" > /var/www/html/index.html
sudo service nginx restart
