#!/usr/bin/env bash
# displays indefinitely, With a sleep 2 and I am invincible SIGTERM signal
trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
